### PR TITLE
fstrim

### PR DESCRIPTION
**Pull request by lgrootnoob**
I apologize for this being several requests. i'd rather not clone more shit than i have to.

### CODE REVIEW

**Comment by lgrootnoob** [comment]
f2fs automatically trims. see https://plus.google.com/+ChetKener/posts/7No16fUQaFz

**Comment by lgrootnoob** [comment]
apparently, f2fs auto wear levels, but not trim. this is much quicker than using discard for writing.

**Comment by sultanqasim** [comment]
Have you tried a benchmark to verify this?

From what I understand, f2fs does trim in a fairly intelligent manner (background trim, queuing/batching trim operations etc.) Enabling the discard option allows f2fs to do it's trim. Writing to a dirty piece of flash will require that it be wiped before it can be rewritten. Writing to a clean piece of memory should be faster than writing to a dirty one. That's the whole point of trim.

Now, with ext4, it didn't do trim in a very intelligent manner, so it just discarded as you deleted files. Thus, discard slowed down the erasing of files significantly on ext4, and periodic fstrim was preferred. The f2fs filesystem is supposed to do trim more intelligently, so that enabling the discard option shouldn't significantly harm file deletion performance.

Could you try making a build with your patch and verifying that using fstrim manually and disabling discard actually speeds up what you are trying to speed up?

Thanks

**Comment by sultanqasim** [comment]
This might be a good document to read:
https://www.kernel.org/doc/Documentation/filesystems/f2fs.txt

**Comment by lgrootnoob** [comment]
ah, so only ext4 does it innefficiently....
Thanks for teaching me something.
i'm building for something else at the moment(which you just indirectly contributed to). i'l do benches there when I get to it. cheers!

**Pull request closed without merging**
